### ISSUE TITLE
Leading/trailing whitespace issue with text response updates

### ISSUE THREAD

**Issue by askyel** [amaatouq/artwork_gender_bias#1]
Currently, [a workaround](https://github.com/amaatouq/artwork_gender_bias/blob/master/client/game/TaskResponseText.jsx#L11) is used to update the text input response such that leading or trailing whitespace can exist on user input. The `round.set` and `round.get` cycle to update the value of the text input erases any leading or trailing whitespace, so without the workaround the user can't add any whitespace as they type.

**Comment by amaatouq** [comment]
Please report the problem here: https://github.com/empiricaly/meteor-empirica-core/issues
